
    drop table bwnote_subs if exists;

    create table bwnote_subs (
        bwnote_id bigint generated by default as identity,
        bwnote_seq integer not null,
        bwnote_subid varchar(250) not null,
        bwnote_trans char(255) not null,
        bwnote_conname varchar(100),
        bwnote_phref varchar(500) not null,
        bwnote_lrefresh varchar(20),
        bwnote_lstatus varchar(100),
        bwnote_errorct integer,
        bwnote_missing char(255) not null,
        bwnote_uri varchar(500),
        bwnote_props varchar(2147483647),
        primary key (bwnote_id)
    );
create index bwnoteidx_subid on bwnote_subs (bwnote_subid);
create index bwnoteidx_phref on bwnote_subs (bwnote_phref);

    alter table bwnote_subs 
        add constraint UK_dumuiwx6roty7oeuuj8y501hj unique (bwnote_subid);
